seos/apps/pos/urls.py
from django.conf.urls import url

from . import views

app_name = 'pos'

urlpatterns = [
    url(r'^provincias/$', views.ListProvinciaView.as_view(), name='provincias_list'),
    url(r'^provincia/new', views.provincia_new, name='provincia_new'),
    url(r'^provincia/(?P<pk>[0-9]+)/$', views.provincia_detail, name='provincia_detail'),
    url(r'^provincia/(?P<pk>[0-9]+)/edit/$', views.provincia_edit, name='provincia_edit'),
    url(r'^ciudades/$', views.ListCiudadesView.as_view(), name='ciudades_list'),
    url(r'^ciudad/new', views.ciudad_new, name='ciudad_new'),
    url(r'^ciudad/(?P<pk>[0-9]+)/$', views.ciudad_detail, name='ciudad_detail'),
    url(r'^ciudad/(?P<pk>[0-9]+)/edit/$', views.ciudad_edit, name='ciudad_edit'),
    url(r'^$', views.index, name='index'),
]

seos/pos/urls.py
from django.conf.urls import url

from . import views

app_name = 'pos'

urlpatterns = [
    url(r'^provincias/$', views.ListProvinciaView.as_view(), name='provincias_list'),
    url(r'^provincia/new', views.provincia_new, name='provincia_new'),
    url(r'^provincia/(?P<pk>[0-9]+)/$', views.provincia_detail, name='provincia_detail'),
    url(r'^provincia/(?P<pk>[0-9]+)/edit/$', views.provincia_edit, name='provincia_edit'),
    url(r'^ciudades/$', views.ListCiudadesView.as_view(), name='ciudades_list'),
    url(r'^ciudad/new', views.ciudad_new, name='ciudad_new'),
    url(r'^ciudad/(?P<pk>[0-9]+)/$', views.ciudad_detail, name='ciudad_detail'),
    url(r'^ciudad/(?P<pk>[0-9]+)/edit/$', views.ciudad_edit, name='ciudad_edit'),
    url(r'^$', views.index, name='index'),
]

seos/seos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, \
    password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^pos/', include('apps.pos.urls')),
    url(r'^sistema/', include('apps.sistema.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/', login, {'template_name': 'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,
        {'template_name': 'registration/password_reset_form.html',
         'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

seos/apps/pos/models.py
from __future__ import unicode_literals

from django.db import models

ACTIVO = 'A'
INACTIVO = 'I'

ESTADOS = [
    (ACTIVO, 'Activo'),
    (INACTIVO, 'Inactivo'),
]


class Provincia(models.Model):
    codigo = models.CharField(max_length=2, primary_key=True, db_column='proCodigo')
    nombre = models.CharField(max_length=25, db_column='proNombre')
    area = models.CharField(max_length=2, db_column='proArea')

    class Meta:
        db_table = 'pos_provincias'

    def __str__(self):
        return self.nombre


class Ciudad(models.Model):
    codigo = models.CharField(max_length=4, primary_key=True, db_column='ciuCodigo')
    nombre = models.CharField(max_length=25, db_column='ciuNombre')
    provincia = models.ForeignKey(Provincia,
                                  models.SET_NULL,
                                  blank=True,
                                  null=True,
                                  db_column='proCodigo')

    class Meta:
        db_table = 'pos_ciudades'

    def estado_nombre(self):
        if self.estado == 'A':
            return 'Activo'
        else:
            return 'Inactivo'

    def __str__(self):
        return self.nombre

seos/apps/pos/forms.py
from django import forms

from .models import Provincia, Ciudad


class ProvinciaForm(forms.ModelForm):
    class Meta:
        model = Provincia
        fields = ('codigo', 'nombre', 'area', )


class CiudadForm(forms.ModelForm):
    class Meta:
        model = Ciudad
        fields = ('codigo', 'nombre', 'provincia', )

seos/apps/pos/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView

from .models import Provincia, Ciudad

from .forms import ProvinciaForm, CiudadForm


@login_required
def index(request):
    return HttpResponse("Hello, world. You're at the pos index.")


@login_required
def provincia_new(request):
    if request.method == "POST":
        form = ProvinciaForm(request.POST)
        if form.is_valid():
            provincia = form.save()
            provincia.save()
            return redirect('pos:provincia_detail', pk=provincia.pk)
    else:
        form = ProvinciaForm()
    return render(request, 'pos/provincia_edit.html', {'form':form})


@login_required
def provincia_detail(request, pk):
    provincia = get_object_or_404(Provincia, pk=pk)
    return render(request, 'pos/provincia_detail.html', {'provincia': provincia})


@login_required
def provincia_edit(request, pk):
    provincia = get_object_or_404(Provincia, pk=pk)
    if request.method == "POST":
        form = ProvinciaForm(data=request.POST, instance=provincia)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('pos:provincia_detail', pk=post.pk)
        else:
            print('No valid form.')
    else:
        form = ProvinciaForm(instance=provincia)
    return render(request, 'pos/provincia_edit.html', {'provincia': provincia})


@login_required
def ciudad_new(request):
    provincias = Provincia.objects.all()
    if request.method == "POST":
        form = CiudadForm(request.POST)
        if form.is_valid():
            ciudad = form.save()
            ciudad.save()
            return redirect('pos:ciudad_detail', pk=ciudad.pk)
    else:
        form = CiudadForm()
    return render(request, 'pos/ciudad_edit.html', {'form':form, 'provincias': provincias})


@login_required
def ciudad_detail(request, pk):
    ciudad = get_object_or_404(Ciudad, pk=pk)
    return render(request, 'pos/ciudad_detail.html', {'ciudad': ciudad})


@login_required
def ciudad_edit(request, pk):
    ciudad = get_object_or_404(Ciudad, pk=pk)
    provincias = Provincia.objects.all()
    if request.method == "POST":
        form = CiudadForm(data=request.POST, instance=ciudad)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('pos:ciudad_detail', pk=post.pk)
        else:
            print('No valid form.')
    else:
        form = CiudadForm()
    return render(request, 'pos/ciudad_edit.html', {'ciudad': ciudad, 'provincias': provincias})


@login_required
class ListProvinciaView(ListView):
    model = Provincia
    template_name = 'pos/provincias_list.html'
    context_object_name = 'provincias_list_all'
    paginate_by = 10

    def get_queryset(self):
        return Provincia.objects.all().order_by('nombre')


@login_required
class DetailProvinciaView(DetailView):
    model = Provincia
    template_name = 'pos/provincia_detail.html'

    def get_queryset(self):
        return Provincia.objects.all()


@login_required
class CreateProvinciaView(CreateView):
    model = Provincia
    fields = '__all__'
    template_name = 'pos/provincia_edit.html'

    def get_success_url(self):
        return reverse('provincias_list')


@login_required
class ListCiudadesView(ListView):
    model = Ciudad
    template_name = 'pos/ciudades_list.html'
    context_object_name = 'ciudades_list_all'
    paginate_by = 15

    def get_queryset(self):
        return Ciudad.objects.all().order_by('nombre')


@login_required
class DetailCiudadView(DetailView):
    model = Ciudad
    template_name = 'pos/ciudad_detail.html'


@login_required
class CreateCiudadView(CreateView):
    model = Ciudad
    fields = '__all__'
    template_name = 'pos/ciudad_edit.html'

    def get_success_url(self):
        return reverse('ciudades_list')

seos/pos/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView

from .models import Provincia, Ciudad

from .forms import ProvinciaForm, CiudadForm


def index():
    return HttpResponse("Hello, world. You're at the pos index.")


def provincia_new(request):
    if request.method == "POST":
        form = ProvinciaForm(request.POST)
        if form.is_valid():
            provincia = form.save()
            provincia.save()
            return redirect('pos:provincia_detail', pk=provincia.pk)
    else:
        form = ProvinciaForm()
    return render(request, 'pos/provincia_edit.html', {'form':form})


def provincia_detail(request, pk):
    provincia = get_object_or_404(Provincia, pk=pk)
    return render(request, 'pos/provincia_detail.html', {'provincia': provincia})


def provincia_edit(request, pk):
    provincia = get_object_or_404(Provincia, pk=pk)
    if request.method == "POST":
        form = ProvinciaForm(data=request.POST, instance=provincia)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('pos:provincia_detail', pk=post.pk)
        else:
            print('No valid form.')
    else:
        form = ProvinciaForm(instance=provincia)
    return render(request, 'pos/provincia_edit.html', {'provincia': provincia})


def ciudad_new(request):
    provincias = Provincia.objects.all()
    if request.method == "POST":
        form = CiudadForm(request.POST)
        if form.is_valid():
            ciudad = form.save()
            ciudad.save()
            return redirect('pos:ciudad_detail', pk=ciudad.pk)
    else:
        form = CiudadForm()
    return render(request, 'pos/ciudad_edit.html', {'form':form, 'provincias': provincias})


def ciudad_detail(request, pk):
    ciudad = get_object_or_404(Ciudad, pk=pk)
    return render(request, 'pos/ciudad_detail.html', {'ciudad': ciudad})


def ciudad_edit(request, pk):
    ciudad = get_object_or_404(Ciudad, pk=pk)
    provincias = Provincia.objects.all()
    if request.method == "POST":
        form = CiudadForm(data=request.POST, instance=ciudad)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('pos:ciudad_detail', pk=post.pk)
        else:
            print('No valid form.')
    else:
        form = CiudadForm()
    return render(request, 'pos/ciudad_edit.html', {'ciudad': ciudad, 'provincias': provincias})


class ListProvinciaView(ListView):
    model = Provincia
    template_name = 'pos/provincias_list.html'
    context_object_name = 'provincias_list_all'
    paginate_by = 10

    def get_queryset(self):
        return Provincia.objects.all().order_by('nombre')


class DetailProvinciaView(DetailView):
    model = Provincia
    template_name = 'pos/provincia_detail.html'

    def get_queryset(self):
        return Provincia.objects.all()


class CreateProvinciaView(CreateView):
    model = Provincia
    fields = '__all__'
    template_name = 'pos/provincia_edit.html'

    def get_success_url(self):
        return reverse('provincias_list')


class ListCiudadesView(ListView):
    model = Ciudad
    template_name = 'pos/ciudades_list.html'
    context_object_name = 'ciudades_list_all'
    paginate_by = 15

    def get_queryset(self):
        return Ciudad.objects.all().order_by('nombre')


class DetailCiudadView(DetailView):
    model = Ciudad
    template_name = 'pos/ciudad_detail.html'


class CreateCiudadView(CreateView):
    model = Ciudad
    fields = '__all__'
    # template_name = 'pos/ciudad_edit.html'

    def get_success_url(self):
        return reverse('ciudades_list')

seos/templates/pos/ciudad_detail.html
{% extends 'base/baseMain.html' %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="row col s12">
            <h3 class="header">Detalle de la Ciudad</h3>
        </div>
    </div>
    <div class="row">
        <form action="" method="POST" class="col s12">
            {% csrf_token %}
            <div class="input-field col s12">
                <i class="material-icons prefix">vpn_key</i>
                <label for="codigo">Código:</label>
                <input id="codigo" type="text" name="codigo" value="{{ ciudad.codigo }}" disabled>
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">short_text</i>
                <label for="nombre">Nombre:</label>
                <input id="nombre" type="text" name="nombre" value="{{ ciudad.nombre }}" disabled>
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">short_text</i>
                <label for="provincia">Provincia:</label>
                <input id="provincia" type="text" name="provincia" value="{{ ciudad.provincia.nombre }}" disabled>
            </div>
            <a class="waves-effect waves-light btn green lighten-2" href="{% url 'pos:ciudad_edit' pk=ciudad.pk %}">Editar</a>
            <a class="waves-effect waves-light btn" href="{% url 'pos:ciudades_list' %}">Regresar</a>
        </form>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

seos/templates/pos/ciudad_edit.html
{% extends 'base/baseMain.html' %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="row col s12">
            <h3 class="header">Detalle de la Ciudad</h3>
        </div>
    </div>
    <div class="row">
        <form action="" method="POST" class="col s12">
            {% csrf_token %}
            <div class="input-field col s12">
                <i class="material-icons prefix">vpn_key</i>
                <label for="codigo">Código:</label>
                <input id="codigo" type="text" name="codigo" value="{{ ciudad.codigo }}">
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">short_text</i>
                <label for="nombre">Nombre:</label>
                <input id="nombre" type="text" name="nombre" value="{{ ciudad.nombre }}">
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">short_text</i>
                <select id="provincias" name="provincia">
                  <option value="" disabled selected>Seleccione...</option>
                {% for provincia in provincias %}
                  <option value={{ provincia.codigo }}>{{ provincia.nombre }}</option>
                {% endfor %}
                </select>
                <label for="provincias">Provincia</label>
            </div>
            <button class="btn waves-effect waves-light light-blue lighten-2" type="submit" name="Save" value="register">Listo
                <i class="material-icons right">send</i>
            </button>
            <a class="waves-effect waves-light btn" href="{% url 'pos:ciudades_list' %}">Regresar</a>
        </form>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

seos/templates/pos/ciudades_list.html
{% extends 'base/baseMain.html' %}

{% block header %}
{% endblock %}

{% block content %}
    <h2 class="header">Ciudades</h2>
    <div class="collection">
        {% for ciudad in ciudades_list_all %}
            <a href="{% url 'pos:ciudad_detail' ciudad.pk %}" class="collection-item">
                <span class="badge">
                    <i class="material-icons">send</i>
                </span>{{ ciudad.nombre }}</a>
        {% endfor %}
    </div>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="waves-effect">
                    <a href="?page={{ page_obj.previous_page_number }}">
                        <i class="material-icons">chevron_left</i>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <span>
                        <i class="material-icons">chevron_left</i>
                    </span>
                </li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><a href="#!">{{ i }}</a></li>
                {% else %}
                    <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}">
                        <i class="material-icons">chevron_right</i>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <span>
                        <i class="material-icons">chevron_right</i>
                    </span>
                </li>
            {% endif %}
        </ul>
    {% endif %}
    <a class="waves-effect waves-light btn" href="{% url 'pos:ciudad_new' %}">Nuevo</a>
{% endblock %}

{% block footer %}
{% endblock %}

seos/templates/pos/provincia_detail.html
{% extends 'base/baseMain.html' %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="row col s12">
            <h3 class="header">Detalle de la Provincia</h3>
        </div>
    </div>
    <div class="row">
        <form action="" method="POST" class="col s12">
            {% csrf_token %}
            <div class="input-field col s12">
                <i class="material-icons prefix">vpn_key</i>
                <label for="codigo">Código:</label>
                <input id="codigo" type="text" name="subject" value="{{ provincia.codigo }}" disabled>
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">short_text</i>
                <label for="nombre">Nombre:</label>
                <input id="nombre" type="text" name="subject" value="{{ provincia.nombre }}" disabled>
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">short_text</i>
                <label for="area">Area:</label>
                <input id="area" type="text" name="subject" value="{{ provincia.area }}" disabled>
            </div>
            <a class="waves-effect waves-light btn green lighten-2" href="{% url 'pos:provincia_edit' pk=provincia.pk %}">Editar</a>
            <a class="waves-effect waves-light btn" href="{% url 'pos:provincias_list' %}">Regresar</a>
        </form>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

seos/templates/pos/provincia_edit.html
{% extends 'base/baseMain.html' %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="row col s12">
            <h3 class="header">Detalle de la Provincia</h3>
        </div>
    </div>
    <div class="row">
        <form action="" method="POST" class="col s12">
            {% csrf_token %}
            <div class="input-field col s12">
                <i class="material-icons prefix">vpn_key</i>
                <label for="codigo">Código:</label>
                <input id="codigo" type="text" name="codigo" value="{{ provincia.codigo }}">
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">short_text</i>
                <label for="nombre">Nombre:</label>
                <input id="nombre" type="text" name="nombre" value="{{ provincia.nombre }}">
            </div>
            <div class="input-field col s12">
                <i class="material-icons prefix">short_text</i>
                <label for="area">Area:</label>
                <input id="area" type="text" name="area" value="{{ provincia.area }}">
            </div>
            <button class="btn waves-effect waves-light light-blue lighten-2" type="submit" name="Save" value="register">Listo
                <i class="material-icons right">send</i>
            </button>
            <a class="waves-effect waves-light btn" href="{% url 'pos:provincias_list' %}">Regresar</a>
        </form>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

seos/templates/pos/provincias_list.html
{% extends 'base/baseMain.html' %}

{% block header %}
{% endblock %}

{% block content %}
    <h2 class="header">Provincias</h2>
    <div class="collection">
        {% for provincia in provincias_list_all %}
            <a href="{% url 'pos:provincia_detail' provincia.pk %}" class="collection-item">
                <span class="badge">
                    <i class="material-icons">send</i>
                </span>
                {{ provincia.nombre }}
            </a>
        {% endfor %}
    </div>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="waves-effect">
                    <a href="?page={{ page_obj.previous_page_number }}">
                        <i class="material-icons">chevron_left</i>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <span>
                        <i class="material-icons">chevron_left</i>
                    </span>
                </li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><a href="#!">{{ i }}</a></li>
                {% else %}
                    <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}">
                        <i class="material-icons">chevron_right</i>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <span>
                        <i class="material-icons">chevron_right</i>
                    </span>
                </li>
            {% endif %}
        </ul>
    {% endif %}
    <a class="waves-effect waves-light btn" href="{% url 'pos:provincia_new' %}">Nuevo</a>
{% endblock %}

{% block footer %}
{% endblock %}